#!/bin/bash

function add_custom_alias(){
    cp $(dirname $0)/alias.working ~/.bash_my_alias
    if [ -z "$(grep '## working alias ##' ~/.bashrc)" ]; then
        echo '## working alias ##' >> ~/.bashrc
        echo 'source ~/.bash_my_alias' >> ~/.bashrc
    fi
}

echo 'adding my alias'
add_custom_alias
