#!/bin/bash

VIMFILES="$HOME/.vim_runtime"
path=`dirname $0`

function install_vim(){
    install_gvim
    install_fonts
    copy_configs
    install_plugin_rails
    install_plugin_markdown
    install_plugin_jslint
    install_plugin_snipmate
    install_plugin_tabular
    add_alias
    clean
}

function install_gvim(){
    gvim --version > /dev/null || sudo apt-get install vim-gnome
}

function install_fonts(){
    sudo cp assets/fonts/* /usr/share/fonts/X11/
}

## config plugins
function install_plugin_rails(){
    path="tmp/softwares/vim-rails"
    [ -d "$path" ] || git clone https://github.com/tpope/vim-rails.git $path
    cp -a $path/* $VIMFILES/
}

function install_plugin_markdown(){
    path="tmp/softwares/vim-markdown"
    [ -d "$path" ] || git clone https://github.com/plasticboy/vim-markdown.git $path
    cp -a $path/* $VIMFILES/
}

function install_plugin_jslint(){
    path="tmp/softwares/vim-jslint"
    [ -d "$path" ] || git clone git://github.com/hallettj/jslint.vim.git $path
    cd $path && rake install > /dev/null && cd -
}

function install_plugin_snipmate(){
    path="tmp/softwares/vim-snippets"
    [ -d "$path" ] || git clone https://github.com/qhwa/snipmate-snippets.git $path
    cp -a $path/snippets $VIMFILES/
}

function install_plugin_tabular(){
    path="tmp/softwares/vim-tabular"
    [ -d "$path" ] || git clone git://github.com/godlygeek/tabular.git $path
    cp -a $path/* $VIMFILES/
}

function copy_configs(){
    cp $path/config/.vim_runtime $HOME -a
    cp $path/config/.vimrc $HOME
}

function add_alias(){
    if [ -z "$(grep '## vim alias ##' $HOME/.bashrc)" ]; then
        echo '## vim alias ##' >> $HOME/.bashrc
        echo 'alias gvim="gvim -f"' >> $HOME/.bashrc
    fi
}

function clean(){
    sudo rm -rf $HOME/yankring_history*.txt $HOME/.vim_mru_files
}

install_vim
