#!/bin/bash
# font
[ -e asstes/fonts ] && sudo cp assets/fonts/* /usr/share/fonts/X11/
# software
gvim --version > /dev/null || sudo apt-get install vim-gnome
# vim-files
export VIMFILES="$HOME/.vim_runtime"
path=`dirname $0`
cp $path/config/.vim_runtime ~ -a
cp $path/config/.vimrc ~

## config plugins
function install_plugin_rails(){
    path="tmp/softwares/vim-rails"
    [ -d "$path" ] || git clone https://github.com/tpope/vim-rails.git $path
    cp -a $path/* $VIMFILES/
}

function install_plugin_markdown(){
    path="tmp/softwares/vim-markdown"
    [ -d "$path" ] || git clone https://github.com/plasticboy/vim-markdown.git $path
    cp -a $path/* $VIMFILES/
}

function install_plugin_jslint(){
    path="tmp/softwares/vim-jslint"
    [ -d "$path" ] || git clone git://github.com/hallettj/jslint.vim.git $path
    cd $path && rake install > /dev/null && cd -
}

function install_plugin_snipmate(){
    path="tmp/softwares/vim-snippets"
    [ -d "$path" ] || git clone https://github.com/honza/snipmate-snippets.git $path
    cp -a $path/snippets $VIMFILES/
}

function add_alias(){
    if [ -z "$(grep '## vim alias ##' ~/.bashrc)" ]; then
        echo '## vim alias ##' >> ~/.bashrc
        echo 'alias gvim="gvim -f"' >> ~/.bashrc
    fi
}

install_plugin_rails
install_plugin_markdown
install_plugin_jslint
install_plugin_snipmate
add_alias
sudo rm -rf ~/yankring_history*.txt ~/.vim_mru_files
